In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("../data/Airline_review.csv")

df.head()
df.shape
df.info()
df.isnull().sum()
df.duplicated().sum()
df.describe()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 23171 entries, 0 to 23170
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              23171 non-null  int64
 1   Airline Name            23171 non-null  str
 2   Overall_Rating          23171 non-null  str
 3   Review_Title            23171 non-null  str
 4   Review Date             23171 non-null  str
 5   Verified                23171 non-null  bool
 6   Review                  23171 non-null  str
 7   Aircraft                7129 non-null   str
 8   Type Of Traveller       19433 non-null  str
 9   Seat Type               22075 non-null  str
 10  Route                   19343 non-null  str
 11  Date Flown              19417 non-null  str
 12  Seat Comfort            19016 non-null  float64
 13  Cabin Staff Service     18911 non-null  float64
 14  Food & Beverages        14500 non-null  float64
 15  Ground Service          18378 non-null  float64
 16  Inflight Entertainment  10829 non-null  float64
 17  Wifi & Connectivity     5920 non-null   float64
 18  Value For Money         22105 non-null  float64
 19  Recommended             23171 non-null  str
dtypes: bool(1), float64(7), int64(1), str(11)
memory usage: 3.4 MB

Index(['Unnamed: 0', 'Airline Name', 'Overall_Rating', 'Review_Title',
       'Review Date', 'Verified', 'Review', 'Aircraft', 'Type Of Traveller',
       'Seat Type', 'Route', 'Date Flown', 'Seat Comfort',
       'Cabin Staff Service', 'Food & Beverages', 'Ground Service',
       'Inflight Entertainment', 'Wifi & Connectivity', 'Value For Money',
       'Recommended'],
      dtype='str')

In [7]:
df = df.drop(columns=["Unnamed: 0"])
df.head()

,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,NaN,Solo Leisure,Economy Class,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,Solo Leisure,Economy Class,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no

In [10]:
df["Overall_Rating"].unique()

array([ 9.,  1.,  8.,  2.,  3.,  5.,  6.,  7.,  4., nan])

In [9]:
df["Overall_Rating"] = pd.to_numeric(df["Overall_Rating"], errors="coerce")

In [11]:
df["Overall_Rating"].isnull().sum()

np.int64(842)

In [12]:
df = df.dropna(subset=["Overall_Rating"])

In [13]:
df.shape

(22329, 19)

In [14]:
df["Recommended"].unique()

<StringArray>
['yes', 'no']
Length: 2, dtype: str

In [15]:
df["full_review_text"] = df["Review_Title"] + " " + df["Review"]

In [16]:
df[["Review_Title", "Review", "full_review_text"]].head()

,Review_Title,Review,full_review_text
0,"""pretty decent airline""",Moroni to Moheli. Turned out to be a pretty ...,"""pretty decent airline"" Moroni to Moheli. Tu..."
1,"""Not a good airline""",Moroni to Anjouan. It is a very small airline...,"""Not a good airline"" Moroni to Anjouan. It is..."
2,"""flight was fortunately short""",Anjouan to Dzaoudzi. A very small airline an...,"""flight was fortunately short"" Anjouan to Dz..."
3,"""I will never fly again with Adria""",Please do a favor yourself and do not fly wi...,"""I will never fly again with Adria"" Please d..."
4,"""it ruined our last days of holidays""",Do not book a flight with this airline! My fr...,"""it ruined our last days of holidays"" Do not ..."

In [17]:
import re

In [18]:
def clean_text(text):
    
    text = str(text)
    
    # lowercase
    text = text.lower()
    
    # remove urls
    text = re.sub(r"http\S+", "", text)
    
    # remove special characters
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    
    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

In [19]:
df["clean_review_text"] = df["full_review_text"].apply(clean_text)

In [20]:
df[["full_review_text", "clean_review_text"]].head()

,full_review_text,clean_review_text
0,"""pretty decent airline"" Moroni to Moheli. Tu...",pretty decent airline moroni to moheli turned ...
1,"""Not a good airline"" Moroni to Anjouan. It is...",not a good airline moroni to anjouan it is a v...
2,"""flight was fortunately short"" Anjouan to Dz...",flight was fortunately short anjouan to dzaoud...
3,"""I will never fly again with Adria"" Please d...",i will never fly again with adria please do a ...
4,"""it ruined our last days of holidays"" Do not ...",it ruined our last days of holidays do not boo...